version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=deviceManager
      - DB_USER=alejandroniro
      - DB_PASSWORD=27868071
      - DB_HOST=db  # Nombre del servicio del contenedor MySQL
      - DB_PORT=3306
    command: bash -c "pipenv run python manage.py migrate && pipenv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  # Monta el código en el contenedor

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=deviceManager
      - MYSQL_USER=alejandroniro
      - MYSQL_PASSWORD=27868071
      - MYSQL_ROOT_PASSWORD=rootPassword
    ports:
      - "3307:3306"
