# Generated by Django 5.0.2 on 2024-02-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceExecution',
            new_name='Device_execution',
        ),
    ]
