# Generated by Django 5.0.2 on 2024-02-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_devicemanager_historical_failure_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemanager',
            name='execution_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
