# Generated by Django 5.0.2 on 2024-02-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_devicemanager_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField()),
                ('total_success_count', models.PositiveIntegerField(default=0)),
                ('total_failure_count', models.PositiveIntegerField(default=0)),
                ('historical_success_count', models.PositiveIntegerField(default=0)),
                ('historical_failure_count', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.device')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceManager',
        ),
    ]
